import type { Locale } from "@/content/i18n";
import { EditorialHeader, EditorialFooter } from "./EditorialHeader";

export function KeychronNote({locale}: {locale: Locale}) {
  const en = locale === "en";
  const t = (zh: string, english: string) => en ? english : zh;
  const sections = [t("结构层次", "Construction"), t("触发深度", "Actuation"), t("复位行为", "Reset behavior"), t("连接方式", "Connectivity"), t("兼容边界", "Compatibility"), t("配置体验", "Configuration")];
  return <>
    <a className="skip-link" href="#main-content">{t("跳到主要内容", "Skip to content")}</a>
    <EditorialHeader locale={locale} article />
    <main id="main-content" className="note-page page-width">
      <div className="note-breadcrumb"><a href={en ? "/en/#writing" : "/#writing"}>{t("全部写作", "All writing")}</a><span>PRODUCT NOTES / 001</span></div>
      <header className="note-heading"><p className="eyebrow">CHINA PRODUCT NOTES</p><h1>{t("一把键盘，", "One keyboard.")}<br /><em>{t("六个工程选择。", "Six engineering choices.")}</em></h1><p className="note-deck">{t("Keychron Q1 HE：从结构、触发到配置，理解“可定制”的具体含义。", "Keychron Q1 HE: a closer look at what a custom keyboard lets you change.")}</p><div className="note-byline"><span>Shaoxiao Xu</span><time dateTime="2026-10-09">{t("2026 年 10 月 9 日", "9 October 2026")}</time><span>{t("资料研究 · 非上手评测", "Desk research · Not a hands-on review")}</span></div></header>
      <div className="note-layout"><aside className="note-index"><p className="eyebrow">{t("本文内容", "IN THIS NOTE")}</p><nav aria-label={t("文章目录", "Article contents")}>{sections.map((label,i)=><a key={label} href={`#choice-${i+1}`}><span>0{i+1}</span>{label}</a>)}<a href="#sources">{t("来源与研究范围", "Sources & scope")}</a></nav><a className="text-link" href="/notes/keychron-product-breakdown.pdf" download>{t("下载英文图解 PDF", "Download the visual PDF")}</a></aside>
      <article className="note-body"><div className="research-scope"><span className="eyebrow">{t("先说明研究范围", "RESEARCH SCOPE")}</span><p>{t("本文针对原版 Q1 HE，不是 Q1 HE 8K。图解与动画为原创概念示意，不按比例；没有独立测试手感、声音、无线稳定性或端到端延迟。图解中的规格核查日期为 2026 年 10 月 7 日。", "This note covers the original Q1 HE, not the Q1 HE 8K. The original diagrams and animation are simplified and not to scale. Sound, feel, wireless stability and end-to-end latency have not been independently tested. Specifications in the visual kit were checked on 7 October 2026.")}</p></div>
      <p className="note-lead">{t("看一把定制键盘，我更想问：用户究竟在定制哪一层？一份功能清单告诉你能调什么，却不会告诉你什么设置适合自己的工作。", "What are you actually customizing in a custom keyboard? A feature list tells you what is adjustable. It does not tell you which settings will suit your work.")}</p>
      <section id="choice-1"><span className="eyebrow">01 / CONSTRUCTION</span><h2>{t("从结构层次开始理解。", "Start with the stack.")}</h2><p>{t("外壳、支撑、定位板、电路板与缓冲层承担不同任务。拆成层次，是为了看清设计选择如何组合，而不是从示意图预测声音和手感。", "The case, support, plate, PCB and damping have different jobs. Separating them helps explain how design choices fit together. A drawing cannot establish sound or feel.")}</p><figure><img src="/notes/card-2.png" width="1080" height="1080" alt={t("键盘不同结构层的原创示意图", "Original explanatory diagram of keyboard layers")} /><figcaption>{t("结构概念示意。层次用于解释，不代表精确装配图。", "A conceptual stack, not an exact assembly drawing.")}</figcaption></figure><p className="test-question">{t("我会测试：长时间打字时，这些结构带来的反馈是否舒适？", "I would test: does the resulting feedback stay comfortable during a long typing session?")}</p></section>
      <section id="choice-2"><span className="eyebrow">02 / ACTUATION</span><h2>{t("决定按到哪里，才算输入。", "Choose when a press registers.")}</h2><p>{t("厂家公布的触发深度调节范围为 0.2–3.8 mm。更浅的设置减少注册输入前的下压行程，但是否适合日常打字，还要考虑误触与重复输入。", "The manufacturer publishes an actuation range of 0.2–3.8 mm. A shallower setting reduces travel before registration. My next question is how it affects unintended presses in ordinary typing.")}</p><figure className="animation-figure"><video controls playsInline preload="none" poster="/notes/card-3.png" width="720" height="720" aria-label={t("触发深度概念动画，无声音，24 秒", "Actuation-depth concept animation, 24 seconds, no audio")}><source src="/notes/actuation-explained.mp4" type="video/mp4" />{t("你的浏览器不支持视频播放。", "Your browser does not support video playback.")}</video><figcaption>{t("24 秒原创概念动画，无音轨。演示浅与深的触发设置，不是产品实拍或实测。", "24-second original concept animation, without audio. It illustrates shallow and deep settings, not a product test.")}</figcaption></figure><details className="video-description"><summary>{t("动画文字说明", "Text description of the animation")}</summary><p>{t("动画比较浅触发与深触发：向下移动较短距离即可注册输入，或需要更深的下压。0.2 mm 和 3.8 mm 是公布范围的端点。动画强调触发深度与实际延迟不是同一个指标。", "The animation compares a shallow and a deep setting. Input registers after a shorter or longer downward movement. The labels 0.2 mm and 3.8 mm are the endpoints of the published range. Actuation depth and real latency are different measures.")}</p></details></section>
      <section id="choice-3"><span className="eyebrow">03 / RESET BEHAVIOR</span><h2>{t("第一次触发，与重复按放分开看。", "The first press is only part of the story.")}</h2><p>{t("Rapid Trigger 涉及连续按下与抬起时的激活、复位行为。首次触发深度与基于移动的复位是不同控制项。一个适合游戏的设置，未必适合写作。", "Rapid Trigger concerns activation and reset during repeated press-release movement. Initial actuation and movement-based reset are separate controls. A preferred gaming setup may not be a preferred writing setup.")}</p><p className="test-question">{t("我会测试：快速重复输入是否稳定，以及普通打字是否出现意外输入。", "I would test: repeatability during rapid input, then unintended inputs during ordinary typing.")}</p></section>
      <section id="choice-4"><span className="eyebrow">04 / CONNECTIVITY</span><h2>{t("报告间隔，不等于完整延迟。", "Reporting rate is not total latency.")}</h2><div className="spec-comparison"><div><span>USB / 2.4 GHz</span><strong>1000 Hz</strong><p>{t("标称报告间隔 1 ms", "1 ms nominal report interval")}</p></div><div><span>Bluetooth</span><strong>90 Hz</strong><p>{t("标称报告间隔约 11.1 ms", "About 11.1 ms nominal interval")}</p></div></div><p>{t("报告间隔的换算是 1000 ÷ 频率（Hz）。这个数值没有测量从手指动作到应用响应的完整路径。若要比较连接模式，我会单独测试稳定性与端到端响应。", "The interval in milliseconds is 1000 divided by frequency in Hz. That calculation does not measure the full path from a finger movement to an application response. I would test connection stability and end-to-end response separately.")}</p></section>
      <section id="choice-5"><span className="eyebrow">05 / COMPATIBILITY</span><h2>{t("热插拔，也有兼容边界。", "Hot-swappable has a boundary.")}</h2><p>{t("原版 Q1 HE 指定了 Gateron 双轨磁轴的兼容范围。能装进相同位置，不代表能与感应系统和固件正确协作。购买替换件前，需要核对确切支持型号。", "The original Q1 HE specifies Gateron double-rail magnetic switches. Physical fit alone does not establish compatibility with the sensing system and firmware. Check the exact supported replacement before ordering.")}</p></section>
      <section id="choice-6"><span className="eyebrow">06 / CONFIGURATION</span><h2>{t("配置，也是产品体验的一部分。", "Configuration is part of ownership.")}</h2><p>{t("Launcher 的配置流程需要有线连接与受支持的浏览器。我关心的是：能否理解当前设置，每次只改变一个行为，并在实际工作中验证，最后恢复到熟悉的配置。", "Launcher configuration requires a cable and a supported browser. My test is simple: can I understand a setting, change one behavior, check it in my actual workflow and restore a familiar setup?")}</p></section>
      <div className="note-takeaway"><span className="eyebrow">{t("我的判断", "MY TAKE")}</span><p>{t("评价定制能力，要看用户能否完成一套适合自己的设置。结构、输入行为、连接与软件，需要一起考虑。", "Evaluate customization as a whole setup: construction, input behavior, connection and software. The useful question is whether a user can arrive at settings that fit their work.")}</p></div>
      <section id="sources" className="note-sources"><span className="eyebrow">SOURCES & SCOPE</span><h2>{t("来源与研究范围", "Sources and research scope")}</h2><p>{t("规格基于厂商公开资料；以下原始链接于 2026 年 10 月 9 日再次访问。本文没有完成工厂、供应商或供应链审计，也没有据此判断长期质量。", "Specifications come from manufacturer materials. These primary-source links were revisited on 9 October 2026. This is not a factory, supplier or supply-chain audit, and it does not establish long-term quality.")}</p><ul><li><a href="https://www.keychron.com/products/keychron-q1-he-qmk-wireless-custom-keyboard" target="_blank" rel="noopener noreferrer">Keychron — Q1 HE product page</a></li><li><a href="https://www.keychron.com/blogs/news/how-to-use-launcher-to-program-your-keyboard" target="_blank" rel="noopener noreferrer">Keychron — Launcher guide</a></li></ul><div className="note-downloads"><a className="button" href="/notes/keychron-product-breakdown.pdf" download>{t("下载 8 页英文图解", "Download the 8-page visual PDF")}</a><a className="text-link" href="/notes/actuation-explained.mp4" download>{t("下载概念动画", "Download the concept animation")}</a></div></section>
      </article></div>
    </main><EditorialFooter locale={locale} />
  </>;
}
